# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 02:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='K1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u1', models.CharField(max_length=32)),
                ('e1', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='K2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u2', models.CharField(max_length=32)),
                ('e2', models.CharField(max_length=32)),
            ],
        ),
    ]
