# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manual', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
        ),
        migrations.RenameModel(
            old_name='K1',
            new_name='UserInfo',
        ),
        migrations.DeleteModel(
            name='K2',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='e1',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='u1',
            new_name='uname',
        ),
    ]
